version: "3.8"

services:
  notes-backend:
    image: jgrove/notes-backend:latest
    container_name: notes-backend
    restart: unless-stopped
    environment:
      # Application Configuration
      SPRING_APPLICATION_NAME: ${SPRING_APPLICATION_NAME}
      SERVER_PORT: ${SERVER_PORT}

      SPRING_DATASOURCE_DRIVER_CLASS_NAME: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

      # JPA/Hibernate Configuration
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      SPRING_JPA_SHOW_SQL: ${SPRING_JPA_SHOW_SQL}
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}

      # JWT Configuration
      JWT_JWKS_URL: ${JWT_JWKS_URL}
      JWT_ALLOWED_ISSUERS: ${JWT_ALLOWED_ISSUERS}

      # Logging Configuration
      LOGGING_LEVEL_ROOT: ${LOGGING_LEVEL_ROOT}
      LOGGING_LEVEL_DEV_JGROVE2_NOTES_BACKEND: ${LOGGING_LEVEL_DEV_JGROVE2_NOTES_BACKEND}

      # Security Configuration
      SECURITY_JWT_ENABLED: ${SECURITY_JWT_ENABLED}
      SECURITY_PUBLIC_PATHS: ${SECURITY_PUBLIC_PATHS}

      # Development Configuration
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}

      # Neon Database Configuration
      SPRING_NEON_URL: ${SPRING_NEON_URL}

      R2_BUCKET_NAME: ${R2_BUCKET_NAME}
      R2_ACCESS_KEY_ID: ${R2_ACCESS_KEY_ID}
      R2_ACCOUNT_ID: ${R2_ACCOUNT_ID}
      R2_SECRET_ACCESS_KEY: ${R2_SECRET_ACCESS_KEY}
      R2_ENDPOINT: ${R2_ENDPOINT}

      UPLOADTHING_API_KEY: ${UPLOADTHING_API_KEY}
      UPLOADTHING_APP_ID: ${UPLOADTHING_APP_ID}
      UPLOADTHING_REGION: ${UPLOADTHING_REGION}
      UPLOADTHING_CALLBACK_URL: ${UPLOADTHING_CALLBACK_URL}
    ports:
      - "3002:3002"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
